version: "3.9"
services:
  # gpu_test:
  #   image: nvidia/cuda:10.2-base
  #   command: nvidia-smi
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: 1
  #             capabilities: [gpu]
  rabbitmq:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_User}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_Pass}
    ports:
      - ${RABBIT_ManagementPort}:15672
      - ${RABBIT_MainPort}:5672

  interface:
    build:
      context: ./docker/ApiServer
      dockerfile: Dockerfile
    ports:
      - ${INTERFACE_Port}:8090
  apiServer:
    build:
      context: ./docker/ApiServer
      dockerfile: Dockerfile
    ports:
      - ${API_Port}:1234
    # depends_on:
    #   - gpu_test
  fileServer:
    build:
      context: ./docker/FileServer
      dockerfile: Dockerfile
    ports:
      - ${FILE_Port}:4321

  modelServer:
    build:
      context: ./docker/ModelServer
      dockerfile: Dockerfile
    ports:
      - ${MODEL_Port}:8000
  frontEnd:
    build:
      context: ./docker/FrontEnd
      dockerfile: Dockerfile
    # ports:
    #   - ${FE_Port}:8000