version: "3.9"
services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_User}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_Pass}
    ports:
      - ${RABBIT_ManagementPort}:15672
      - ${RABBIT_MainPort}:5672
    networks:
      - bridge-net

  interface:
    hostname: interfaceservice
    container_name: interfaceservice
    build:
      context: /docker/Interface
      dockerfile: Dockerfile
    ports:
      - ${INTERFACE_Port}:8090
    networks:
      - bridge-net
    depends_on:
      - rabbitmq

  apiserver:
    hostname: apiservice
    container_name: apiservice
    build:
      context: /docker/ApiServer
      dockerfile: Dockerfile
    ports:
      - ${API_Port}:1234
    networks:
      - bridge-net
    depends_on:
      - rabbitmq
    # depends_on:
    #   - gpu_test

  fileserver:
    hostname: fileservice
    container_name: fileservice
    build:
      context: /docker/FileServer
      dockerfile: Dockerfile
    ports:
      - ${FILE_Port}:4321
    networks:
      - bridge-net
    depends_on:
      - rabbitmq

  modelserver:
    hostname: modelservice
    container_name: modelservice
    build:
      context: /docker/ModelServer
      dockerfile: Dockerfile
    ports:
      - ${MODEL_Port}:8000
    networks:
      - bridge-net
    depends_on:
      - rabbitmq

  frontend:
    hostname: feservice
    container_name: feservice
    build:
      context: /docker/FrontEnd
      dockerfile: Dockerfile
    networks:
      - bridge-net
    ports:
      - ${FE_Port}:8050
    depends_on:
      - rabbitmq

networks:
  bridge-net:
    name: bridge_network
    driver: bridge
